### ISSUE TITLE
odp_packet_dpdk.c-> start_pkt_dpdk->line564(master branch), num_rx_desc should be num_tx_desc

### ISSUE THREAD

**Issue by ieliynehc** [Linaro/odp-dpdk#56]
for (i = 0; i < nbtxq; i++) {
		ret = rte_eth_tx_queue_setup(port_id, i,
					     pkt_dpdk->opt.num_rx_desc,
					     socket_id, txconf);
		if (ret < 0) {
			ODP_ERR("txq:err=%d, port=%" PRIu16 "\n", ret, port_id);
			return -1;
		}
	}

**Comment by muvarov** [comment]
yes, thanks.
