### ISSUE TITLE
odp_ipsec_capability fails

### ISSUE THREAD

**Issue by RadulescuValentin** [Linaro/odp-dpdk#59]
odp_crypto.c:557:odp_crypto_capability():No crypto devices available
E -2090823328 0:3089917952 ofp_ipsec.c:179] odp_ipsec_capability failed
E -2090817028 0:3089917952 app_main.c:351] Error: OFP global init failed.
This issue is escalated from https://github.com/OpenFastPath/ofp/issues/216

**Comment by Bill-Fischofer-Linaro** [comment]
@matiaselo @lumag Any comments on this? 

@RadulescuValentin does this only occur on odp-dpdk? Can you reproduce the issue on odp-linux?

**Comment by Bill-Fischofer-Linaro** [comment]
I did some quick digging and responded on the OFP thread. Sounds like this is an OFP issue to do it not failing gracefully if `odp_crypto_capability()` returns -1.

**Comment by matiaselo** [comment]
Fixed in PR #60.
